version: '3'

services:
  node:
    image: "node:12"
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - ../millipede-guide-content:/app/public/content:ro
      - next_build:/app/build:delegated
      - next_out:/app/out:delegated
      - node_modules:/app/node_modules:delegated
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - www
      - default
    command: sh -c "npm install && npm run dev"

volumes:
  node_modules:
  next_build:
  next_out:

networks:
  www:
    external:
      name: www
