# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TODO: https://github.com/ad-m/github-push-action

name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '33 3 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: millipede-guide/millipede-guide-docs
          path: public/docs
        
      - name: Checkout build
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: out

      - name: Reload original photo files
        run: mv out/photos/orig/* public/photos/orig/

      - name: NPM Install
        run: npm ci
        
      - name: Compile docs
        run: npm run docs

      # - name: Delete original photos
      #   run: rm -rf public/photos/orig
        
      - name: Next.js build
        run: npm run build
        
      - name: Next.js export
        run: npm run export
        
      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
          SINGLE_COMMIT: true
