# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TODO: https://github.com/ad-m/github-push-action

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout build
        uses: actions/checkout@v2
        with:
          repository: millipede-guide/millipede-guide-build
          path: build
        
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: millipede-guide/millipede-guide-docs
          path: build/public/docs

      - run: cd build
      - run: git merge ../main
      - run: npm ci
      - run: npm run docs
      - run: npm run build
      - run: npm run export
