# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TODO: https://github.com/ad-m/github-push-action

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: millipede-guide/millipede-guide-docs
          path: public/docs

      - name: NPM Install
        run: npm ci
        
      - name: Compile docs
        run: npm run docs
        
      - name: Next.js build
        run: npm run build
        
      - name: Next.js export
        run: npm run export
        
      - name: Fix Git Ignore
        run: |
          sed -i '/^\/docs$/d' .gitignore
          echo '/docs/docs' >> .gitignore
          echo '/docs/photos/orig' >> .gitignore
          touch ./docs/.nojekyll
          echo 'www.millipede-guide.com' > ./docs/CNAME

      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
          SINGLE_COMMIT: true
          

