name: Lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run linter
